sudo: required
services:
- docker
os:
- linux
env:
  global:
  - DOCKER_IMAGE_NAME="helloworld"
  - DOCKER_HUB_ORG="ajisepulsa"

before_install:
- openssl aes-256-cbc -K $encrypted_bfaaa201585a_key -iv $encrypted_bfaaa201585a_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
script:
- chmod +x deploy.sh
- chmod 600 deploy_rsa
after_script:
- echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
- docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID} .
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID}
- docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID}
  ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:latest
- ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
- ssh -v -i deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR 'bash -s' < deploy.sh
