sudo: required

services:
  - docker

os:
- linux

env:
  global:
    - DOCKER_IMAGE_NAME="helloworld"
    - DOCKER_HUB_ORG="ajisepulsa"

before_script:
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

script:
- chmod +x deploy.sh
- chmod 600 deploy_rsa

after_script:
- docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID} .
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID}
- docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:latest
- ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
- ssh -v -i deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR 'bash -s' < deploy.sh
