apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: coba
  #kubernetes.io/change-cause: upgrade nginx version
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: nginx:nginx:1.17.6
